"use client";
import {useEffect,useRef,useState} from "react";
import {papers} from "./papers";
import s from "./studio.module.css";
const STORE="hallium:topik-pbt-mocks:v1",SIGNS=["①","②","③","④"];
const byId=id=>papers.find(p=>p.id===id);
const blank=p=>({answers:{},writing:{},section:"listening",seconds:p.minutes*60,running:false,deadline:0,submitted:false,startedAt:null,finishedAt:null});
const qid=(section,i)=>(section==="writing"?"W":section==="listening"?"L":"R")+i;
function count(p,e){return p.sections.reduce((total,section)=>total+Array.from({length:section.count},(_,j)=>!!(section.id==="writing"?e.writing?.[qid(section.id,j+1)]?.trim():e.answers?.[qid(section.id,j+1)])).filter(Boolean).length,0)}
function preview(url){const m=url?.match(/drive\.google\.com\/file\/d\/([\w-]+)/);return m?"https://drive.google.com/file/d/"+m[1]+"/preview":url}
function time(n){n=Math.max(0,Math.ceil(n));return String(Math.floor(n/60)).padStart(2,"0")+":"+String(n%60).padStart(2,"0")}
export default function MockStudio(){
 const [level,setLevel]=useState("I"),[id,setId]=useState(null),[storage,setStorage]=useState({}),[loaded,setLoaded]=useState(false),[confirm,setConfirm]=useState("");
 const last=useRef(0);
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(STORE)||"{}");if(v&&typeof v==="object"&&!Array.isArray(v))setStorage(v)}catch{}const requested=new URLSearchParams(location.search).get("paper");if(byId(requested)){setId(requested);setLevel(byId(requested).level)}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(STORE,JSON.stringify(storage))}catch{}},[storage,loaded]);
 const paper=byId(id),entry=paper?(storage[paper.id]||blank(paper)):null;
 const update=transform=>setStorage(old=>({...old,[paper.id]:transform(old[paper.id]||blank(paper))}));
 useEffect(()=>{if(!paper||!entry?.running||entry.submitted)return;last.current=Date.now();const job=setInterval(()=>{const now=Date.now();if(now-last.current<450)return;last.current=now;update(e=>{if(!e.running||e.submitted)return e;const left=Math.max(0,Math.ceil((e.deadline-now)/1000));return {...e,seconds:left,running:left>0,submitted:left===0,finishedAt:left===0?new Date(now).toISOString():e.finishedAt}})},700);return()=>clearInterval(job)},[id,entry?.running,entry?.submitted]);
 function open(p){setId(p.id);setLevel(p.level);setConfirm("");history.replaceState(null,"","/topik-mocks?paper="+p.id)}
 function close(){setId(null);setConfirm("");history.replaceState(null,"","/topik-mocks")}
 function start(){update(e=>({...e,running:true,deadline:Date.now()+e.seconds*1000,startedAt:e.startedAt||new Date().toISOString()}))}
 function pause(){update(e=>({...e,running:false,deadline:0}))}
 function submit(){update(e=>({...e,running:false,deadline:0,submitted:true,finishedAt:new Date().toISOString()}));setConfirm("")}
 function reset(){update(()=>blank(paper));setConfirm("")}
 const answered=paper?count(paper,entry):0,total=paper?paper.sections.reduce((n,v)=>n+v.count,0):0;
 const current=paper?.sections.find(v=>v.id===entry.section)||paper?.sections[0];
 const source=paper?(current.id==="reading"&&paper.readingPaper?paper.readingPaper:paper.paper):null;
 return <div className={s.root}><header className={s.top}><a className={s.brand} href="/"><span className={s.brandIcon}>ㅎ</span><span>Hallium<small>TOPIK MOCK STUDIO</small></span></a><a className={s.back} href="/">← Hallium home</a></header><main className={s.main}>
 {!paper?<><div className={s.intro}><div><span className={s.eyebrow}>REAL PAST PAPERS / PRACTICE MODE</span><h1>Meet the exam. <em>Before exam day.</em></h1><p>Seven released exam sessions from your TOPIK I and II past-paper compilations. Open the original test paper beside a timed Hallium response sheet, save your answers, and review afterward.</p></div><div className={s.counter}><strong>14</strong><small>Mock papers · I + II</small></div></div><div className={s.tabs} role="group" aria-label="Choose exam level"><button aria-pressed={level==="I"} onClick={()=>setLevel("I")}>TOPIK I · Beginner</button><button aria-pressed={level==="II"} onClick={()=>setLevel("II")}>TOPIK II · Intermediate+</button></div><div className={s.grid}>{papers.filter(p=>p.level===level).map(p=>{const e=storage[p.id]||blank(p),done=count(p,e),maximum=p.sections.reduce((n,x)=>n+x.count,0);return <button key={p.id} className={s.tile} onClick={()=>open(p)}><div className={s.tileTop}><span className={s.pill}>TOPIK {p.level}</span><span>{p.round}회 · Released PBT</span></div><h2>{p.title}</h2><p>{p.sections.map(v=>v.name).join(" · ")}<br/>{p.minutes} minutes · {maximum} response fields</p><div className={s.tileFoot}><span>{e.submitted?"✓ Submitted":done?done+" / "+maximum+" saved":"Start mock →"}</span><span>{done?"Continue ↗":"Open ↗"}</span></div></button>})}</div><p className={s.warning}><strong>About these mocks:</strong> Historical paper-based TOPIK format. The linked original papers, audio, transcripts and answer keys are hosted by public third-party collections. Hallium saves answers on this browser only and does not claim an official or automatically verified score.</p></>:
 <><div className={s.toolbar}><button className={s.mini} onClick={close}>← All papers</button><h1>{paper.title}</h1><span className={s.spacer}/><span className={s.clock} data-low={entry.seconds<300}>{time(entry.seconds)}</span>{entry.submitted?<span className={s.pill}>Submitted</span>:<button className={s.mini} onClick={entry.running?pause:start}>{entry.running?"Pause":entry.startedAt?"Resume timer":"Start timer"}</button>}<button className={s.mini} onClick={()=>setConfirm("reset")}>Reset</button></div>
 <div className={s.columns}><section className={s.paper} aria-label="Original TOPIK paper"><div className={s.panelHead}><strong>{paper.round}회 · Original question paper</strong><a className={s.link} target="_blank" rel="noopener noreferrer" href={source}>Open / download ↗</a></div><iframe key={source} title={paper.title+" paper"} className={s.frame} src={preview(source)} loading="lazy"/><div className={s.paperFoot}>If the preview is blank, use “Open / download.” External PDFs may not permit in-app previews. Use the paper for question text and figures.</div></section>
 <section className={s.answers} aria-label="Timed mock answer sheet"><div className={s.answerHead}><span className={s.eyebrow}>YOUR RESPONSE SHEET · {answered} / {total}</span><h2>Answer alongside the paper.</h2><p>Select the section matching the paper. Your choices and writing are stored locally as you work.</p></div><div className={s.sectionTabs} role="tablist" aria-label="Test sections">{paper.sections.map(sec=><button role="tab" key={sec.id} aria-selected={current.id===sec.id} onClick={()=>update(e=>({...e,section:sec.id}))}>{sec.ko} · {sec.name} {sec.count}</button>)}</div>
 <div className={s.questions}>{current.id==="writing"?Array.from({length:4},(_,j)=>{const k=qid("writing",j+51),val=entry.writing[k]||"";return <label key={k} className={s.writing}><strong>쓰기 · Question {j+51}</strong><textarea lang="ko" aria-label={"Writing answer "+(j+51)} placeholder="한국어로 작성하세요…" disabled={entry.submitted} value={val} onChange={ev=>update(e=>({...e,writing:{...e.writing,[k]:ev.target.value}}))}/><small>{Array.from(val).length} characters · compare with the original paper</small></label>}):Array.from({length:current.count},(_,j)=>{const k=qid(current.id,j+1),value=entry.answers[k];return <div className={s.question} key={k}><div className={s.questionHead}><strong>{current.ko} · {j+1}</strong><small>{value?"Option "+value:"Not answered"}</small></div><div className={s.options}>{SIGNS.map((sign,n)=><button type="button" key={n} disabled={entry.submitted} aria-pressed={value===String(n+1)} aria-label={current.name+" question "+(j+1)+" option "+(n+1)} onClick={()=>update(e=>({...e,answers:{...e.answers,[k]:value===String(n+1)?"":String(n+1)}}))}>{sign}</button>)}</div></div>})}</div>
 <div className={s.resources}><a className={s.link} href={paper.resource} target="_blank" rel="noopener noreferrer">Listening audio ↗</a><a className={s.link} href={paper.resource} target="_blank" rel="noopener noreferrer">Published answer keys ↗</a><a className={s.link} href={paper.resource} target="_blank" rel="noopener noreferrer">Transcript ↗</a>{paper.readingPaper&&current.id!=="reading"&&<a className={s.link} href={paper.readingPaper} target="_blank" rel="noopener noreferrer">Reading PDF ↗</a>}</div>
 {entry.submitted?<div className={s.result} role="status"><strong>Practice submitted ✓</strong><p>{answered} of {total} fields completed. Review the published key using the resource link. Writing requires separate review; this is not an official TOPIK score.</p><a className={s.link} href={paper.resource} target="_blank" rel="noopener noreferrer">Check published answers ↗</a></div>:<div className={s.actions}><span>Answers autosave · timer {entry.running?"running":"paused"}</span><button className={s.primary} onClick={()=>setConfirm("submit")}>Finish mock →</button></div>}
 {confirm&&<div className={s.result} role="alert"><strong>{confirm==="reset"?"Reset this practice?":"Submit your mock?"}</strong><p>{confirm==="reset"?"All answers and the timer for this paper will be cleared. Other papers are unaffected.":answered+" of "+total+" response fields completed. Submitting locks your response sheet until you reset it."}</p><button className={s.primary} onClick={confirm==="reset"?reset:submit}>{confirm==="reset"?"Clear this attempt":"Confirm submission"}</button> <button className={s.mini} onClick={()=>setConfirm("")}>Cancel</button></div>}
 </section></div><p className={s.hint} style={{marginTop:18}}>These mocks are for the paper-based format, not TOPIK IBT. Public resource links are provided instead of republishing the owner's shared Drive PDFs. Your responses do not sync to the main Hallium account.</p></>}
 <footer className={s.foot}><span>HALLIUM · TOPIK PAST PAPER STUDIO</span><span><a href="/">Home</a> · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a></span></footer></main></div>;
}
