"use client";
import {useEffect,useRef,useState} from "react";
import {papers,paperCatalogAudit} from "./papers";
import {provenanceBadge} from "../../lib/topik/provenance";
import {
 buildQuestionManifest,
 examActivationSummary,
 questionAudioCue,
 scoreObjectiveAttempt,
} from "../../lib/topik/exam-engine";
import s from "./studio.module.css";
const STORE="hallium:topik-pbt-mocks:v1",SIGNS=["①","②","③","④"];
const byId=id=>papers.find(p=>p.id===id);
const blank=p=>({answers:{},writing:{},section:"listening",seconds:p.minutes*60,running:false,deadline:0,submitted:false,startedAt:null,finishedAt:null});
const qid=(section,i)=>(section==="writing"?"W":section==="listening"?"L":"R")+i;
function count(p,e){return p.sections.reduce((total,section)=>total+Array.from({length:section.count},(_,j)=>!!(section.id==="writing"?e.writing?.[qid(section.id,j+1)]?.trim():e.answers?.[qid(section.id,j+1)])).filter(Boolean).length,0)}
function preview(url){const m=url?.match(/drive\.google\.com\/file\/d\/([\w-]+)/);return m?"https://drive.google.com/file/d/"+m[1]+"/preview":url}
function time(n){n=Math.max(0,Math.ceil(n));return String(Math.floor(n/60)).padStart(2,"0")+":"+String(n%60).padStart(2,"0")}
export default function MockStudio(){
 const [level,setLevel]=useState("I"),[id,setId]=useState(null),[storage,setStorage]=useState({}),[loaded,setLoaded]=useState(false),[clientReady,setClientReady]=useState(false),[confirm,setConfirm]=useState("");
 const last=useRef(0);
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(STORE)||"{}");if(v&&typeof v==="object"&&!Array.isArray(v))setStorage(v)}catch{}const requested=new URLSearchParams(location.search).get("paper");if(byId(requested)){setId(requested);setLevel(byId(requested).level)}setLoaded(true);setClientReady(true)},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(STORE,JSON.stringify(storage))}catch{}},[storage,loaded]);
 const paper=byId(id),entry=paper?(storage[paper.id]||blank(paper)):null;
 const questionManifest=paper?buildQuestionManifest(paper):[];
 const activation=paper?examActivationSummary(paper):null;
 const scoreResult=paper&&entry?.submitted?scoreObjectiveAttempt(paper,entry.answers):null;
 const update=transform=>setStorage(old=>({...old,[paper.id]:transform(old[paper.id]||blank(paper))}));
 useEffect(()=>{if(!paper||!entry?.running||entry.submitted)return;last.current=Date.now();const job=setInterval(()=>{const now=Date.now();if(now-last.current<450)return;last.current=now;update(e=>{if(!e.running||e.submitted)return e;const left=Math.max(0,Math.ceil((e.deadline-now)/1000));return {...e,seconds:left,running:left>0,submitted:left===0,finishedAt:left===0?new Date(now).toISOString():e.finishedAt}})},700);return()=>clearInterval(job)},[id,entry?.running,entry?.submitted]);
 function open(p){setId(p.id);setLevel(p.level);setConfirm("");history.replaceState(null,"","/topik-mocks?paper="+p.id)}
 function close(){setId(null);setConfirm("");history.replaceState(null,"","/topik-mocks")}
 function start(){update(e=>({...e,running:true,deadline:Date.now()+e.seconds*1000,startedAt:e.startedAt||new Date().toISOString()}))}
 function pause(){update(e=>({...e,running:false,deadline:0}))}
 function submit(){update(e=>({...e,running:false,deadline:0,submitted:true,finishedAt:new Date().toISOString()}));setConfirm("")}
 function reset(){update(()=>blank(paper));setConfirm("")}
 function playVerifiedAudio(cue){
  if(!cue?.src||typeof window==="undefined")return;
  try{
   const audio=new Audio(cue.src);
   audio.preload="auto";
   audio.currentTime=Math.max(0,Number(cue.start||0));
   let timer=null;
   const stop=()=>{if(timer)window.clearInterval(timer);audio.pause();};
   audio.addEventListener("play",()=>{
    if(cue.end!=null)timer=window.setInterval(()=>{if(audio.currentTime>=Number(cue.end))stop()},120);
   },{once:true});
   audio.play().catch(()=>{});
  }catch{}
 }
 const answered=paper?count(paper,entry):0,total=paper?paper.sections.reduce((n,v)=>n+v.count,0):0;
 const current=paper?.sections.find(v=>v.id===entry.section)||paper?.sections[0];
 const source=paper?(current.id==="reading"&&paper.readingPaper?paper.readingPaper:current.id==="writing"&&paper.writingPaper?paper.writingPaper:paper.paper):null;
 const gate=paper?.provenanceAudit||null;
 const audioLabel=gate?.audio==="BLOCKED"?"Listening MP3 · blocked pending audit":gate?.audio==="VERIFIED"?"Listening MP3 · verified":"Listening MP3 · unverified";
 const keyLabel=gate?.answerKey==="VERIFIED"?"Answer key · verified":"Answer key · not audited";
 const resources=paper?([{label:"Source archive",href:paper.resource},{label:"Listening PDF",href:paper.paper},{label:"Writing PDF",href:paper.writingPaper},{label:"Reading PDF",href:paper.readingPaper},{label:audioLabel,href:paper.audio},{label:"Listening transcript",href:paper.transcript},...(paper.answerKeys?Object.entries(paper.answerKeys).map(([kind,href])=>({label:kind==="combined"?keyLabel:kind+" key · "+(gate?.answerKey==="VERIFIED"?"verified":"not audited"),href})):[])]).filter(x=>!!x.href):[];
 const plainStatus=paper?{
  title:activation?.scoring==="ready"||activation?.audio==="ready"?"Verified interactive features available":"Practice mode only",
  detail:[
   activation?.scoring==="ready"?"Hallium can grade the verified objective sections after submission.":"Hallium will save your responses but will not grade this paper yet.",
   activation?.audio==="ready"?"Verified question audio is available where mapped.":"Use the original source audio externally until Hallium's audio map is verified.",
  ].join(" ")
 }:null;
 return <div className={s.root} data-client-ready={clientReady?"true":"false"}><header className={s.top}><a className={s.brand} href="/"><span className={s.brandIcon}>ㅎ</span><span>Hallium<small>TOPIK MOCK STUDIO</small></span></a><a className={s.back} href="/">← Hallium home</a></header><main className={s.main}>
 {!paper?<><div className={s.intro}><div><span className={s.eyebrow}>REAL PAST PAPERS / PRACTICE MODE</span><h1>Meet the exam. <em>Before exam day.</em></h1><p>Four newer source-linked releases for TOPIK I and four for TOPIK II, plus the older sessions already in your collection. Open source papers beside a timed practice answer sheet. Audio and automatic scoring require further verification.</p></div><div className={s.counter}><strong>{papers.length}</strong><small>Practice sessions · I + II</small><span className={paperCatalogAudit.valid?s.catalogOk:s.catalogWarn}>{paperCatalogAudit.valid?"Structure gate passed":"Catalog needs review"}</span></div></div><div className={s.tabs} role="group" aria-label="Choose exam level"><button aria-pressed={level==="I"} onClick={()=>setLevel("I")}>TOPIK I · Beginner</button><button aria-pressed={level==="II"} onClick={()=>setLevel("II")}>TOPIK II · Intermediate+</button></div><div className={s.grid}>{papers.filter(p=>p.level===level).map(p=>{const e=storage[p.id]||blank(p),done=count(p,e),maximum=p.sections.reduce((n,x)=>n+x.count,0);return <button key={p.id} className={s.tile} onClick={()=>open(p)}><div className={s.tileTop}><span className={s.pill}>TOPIK {p.level}</span><span>{p.round}회 · PBT {p.oldPaper?"· legacy source pending":"· newly indexed"}</span></div><span className={s.provenanceBadge} data-state={p.provenanceAudit?.activationState||"UNKNOWN"}>{provenanceBadge(p.provenanceAudit)}</span><h2>{p.title}</h2><p>{p.sections.map(v=>v.name).join(" · ")}<br/>{p.minutes} minutes · {maximum} response fields</p><div className={s.tileFoot}><span>{e.submitted?"✓ Submitted":done?done+" / "+maximum+" saved":"Start mock →"}</span><span>{done?"Continue ↗":"Open ↗"}</span></div></button>})}</div><p className={s.warning}><strong>About these mocks:</strong> Historical paper-based TOPIK format. Some older source links are pending verification. The newer source-linked rounds expose separate question PDFs and supporting assets where available; MP3 content and complete keys are NOT verified. Hallium links to external sources without rehosting original files. Copyright permission for embedded or interactive use is pending. Your answers stay on this browser. Automatic scoring appears only for papers whose exact key and point map pass Hallium's verification gate; Hallium scores are never official TOPIK results.</p></>:
 <><div className={s.toolbar}><button className={s.mini} onClick={close}>← All papers</button><h1>{paper.title}</h1><span className={s.spacer}/><span className={s.clock} data-low={entry.seconds<300}>{time(entry.seconds)}</span>{entry.submitted?<span className={s.pill}>Submitted</span>:<button className={s.mini} onClick={entry.running?pause:start}>{entry.running?"Pause":entry.startedAt?"Resume timer":"Start timer"}</button>}<button className={s.mini} onClick={()=>setConfirm("reset")}>Reset</button></div>
 <div className={s.columns}><section className={s.paper} aria-label="Original TOPIK paper"><div className={s.panelHead}><strong>{paper.round}회 · {source?"Source question paper":"Paper source pending audit"}</strong>{source&&<a className={s.link} target="_blank" rel="noopener noreferrer" href={source}>Open original ↗</a>}</div>{source?<iframe key={source} title={paper.title+" source paper"} className={s.frame} src={preview(source)} loading="lazy"/>:<div className={s.sourcePending}><strong>Source link not yet verified</strong><p>The previous direct link was not authenticated and has been withdrawn. You can consult the external examination archive while we verify an original PDF source.</p><a className={s.link} href={paper.resource} target="_blank" rel="noopener noreferrer">Visit source archive ↗</a></div>}<div className={s.paperFoot}>External source preview may be unavailable or require permission. Open original on its hosting site. Hallium does not host or certify these exam files.</div></section>
 <section className={s.answers} aria-label="Timed mock answer sheet"><div className={s.answerHead}><span className={s.eyebrow}>YOUR RESPONSE SHEET · {answered} / {total}</span><h2>Answer alongside the paper.</h2><p>Select the section matching the paper. Your choices and writing are stored locally as you work.</p></div><div className={s.sectionTabs} role="tablist" aria-label="Test sections">{paper.sections.map(sec=><button role="tab" key={sec.id} aria-selected={current.id===sec.id} onClick={()=>update(e=>({...e,section:sec.id}))}>{sec.ko} · {sec.name} {sec.count}</button>)}</div>
 <div className={s.questions}>{current.id==="writing"?Array.from({length:4},(_,j)=>{const k=qid("writing",j+1),val=entry.writing[k]||"";return <label key={k} className={s.writing}><strong>쓰기 · Question {j+51}</strong><textarea lang="ko" aria-label={"Writing answer "+(j+51)} placeholder="한국어로 작성하세요…" disabled={entry.submitted} value={val} onChange={ev=>update(e=>({...e,writing:{...e.writing,[k]:ev.target.value}}))}/><small>{Array.from(val).length} characters · compare with the original paper</small></label>}):Array.from({length:current.count},(_,j)=>{const k=qid(current.id,j+1),value=entry.answers[k],cue=current.id==="listening"?questionAudioCue(paper,k):null;return <div className={s.question} key={k}><div className={s.questionHead}><strong>{current.ko} · {current.id==="reading"&&paper.level==="I"?j+31:j+1}</strong><div className={s.questionStatus}>{cue&&<button type="button" className={s.audioCue} onClick={()=>playVerifiedAudio(cue)}>▶ Verified audio</button>}<small>{value?"Option "+value:"Not answered"}</small></div></div><div className={s.options}>{SIGNS.map((sign,n)=><button type="button" key={n} disabled={entry.submitted} aria-pressed={value===String(n+1)} aria-label={current.name+" question "+(j+1)+" option "+(n+1)} onClick={()=>update(e=>({...e,answers:{...e.answers,[k]:value===String(n+1)?"":String(n+1)}}))}>{sign}</button>)}</div></div>})}</div>
 <div className={s.featureNotice} role="note"><strong>{plainStatus.title}</strong><span>{plainStatus.detail}</span></div>
 <section className={s.provenancePanel} aria-label="TOPIK provenance gate"><div className={s.provenanceHead}><div><span>PROVENANCE GATE</span><strong>{provenanceBadge(gate)}</strong></div><em data-state={gate?.activationState||"UNKNOWN"}>{gate?.activationState||"UNKNOWN"}</em></div><div className={s.provenanceGrid}><div><small>Release</small><b>{gate?.releaseState||"UNAUDITED"}</b></div><div><small>Booklet</small><b>{gate?.booklet||"PENDING"}</b></div><div><small>Answer key</small><b>{gate?.answerKey||"PENDING"}</b></div><div><small>Transcript</small><b>{gate?.transcript||"PENDING"}</b></div><div><small>Audio</small><b>{gate?.audio||"PENDING"}</b></div><div><small>Rights</small><b>{gate?.rights||"PENDING"}</b></div></div><p>{gate?.sourceBasis||paper.provenance}</p>{gate?.quarantineReason&&<p className={s.provenanceReason}><strong>Activation gate:</strong> {gate.quarantineReason}</p>}<div className={s.provenanceFlags}><span data-allowed={activation?.scoring==="ready"}>Auto scoring · {activation?.scoring==="ready"?"ready":"locked"}</span><span data-allowed={activation?.audio==="ready"}>Question audio · {activation?.audio==="ready"?"ready":"locked"}</span><span data-allowed={!!gate?.inAppQuestionContentAllowed}>Question reproduction · {gate?.inAppQuestionContentAllowed?"allowed":"locked"}</span></div><div className={s.engineMeta}><span>{questionManifest.length} mapped response fields</span><span>{activation?.scoring==="ready"?"Verified score bundle loaded":"Score bundle unavailable"}</span><span>{activation?.audio==="ready"?"Verified audio map loaded":"Audio map unavailable"}</span></div></section>
 <div className={s.resources}>{resources.map(x=><a key={x.label} className={s.link} href={x.href} target="_blank" rel="noopener noreferrer">{x.label} ↗</a>)}</div><div className={s.auditNote}><strong>Verification:</strong> {paper.sourceStatus}. {paper.audioStatus}. {paper.scoreStatus}. {paper.oldPaper?"Existing browser answers are preserved.":""}</div>
 {entry.submitted?<div className={s.result} role="status">{scoreResult?.status==="scored"?<><strong>Verified objective score · {scoreResult.earned} / {scoreResult.possible}</strong><p>{scoreResult.correct} correct · {scoreResult.incorrect} incorrect · {scoreResult.unanswered} unanswered · {scoreResult.percent}% of verified available points.</p><div className={s.scoreSections}>{scoreResult.sections.map(section=><span key={section.section}><b>{section.section}</b>{section.earned} / {section.possible}</span>)}</div><small>Key bundle {scoreResult.bundleVersion} · verified {new Date(scoreResult.verifiedAt).toLocaleDateString()}{paper.level==="II"?" · writing score not included":""}</small></>:<><strong>Practice submitted ✓ · scoring locked</strong><p>{answered} of {total} fields completed. Your responses are saved, but Hallium will not grade this paper until an exact key and point map pass the provenance gate.</p><span className={s.lockReason}>{scoreResult?.reason||gate?.quarantineReason||"Verified scoring assets are not active for this paper."}</span><a className={s.link} href={paper.resource} target="_blank" rel="noopener noreferrer">Check published source ↗</a></>}</div>:<div className={s.actions}><span>Answers autosave · timer {entry.running?"running":"paused"}</span><button className={s.primary} onClick={()=>setConfirm("submit")}>Finish mock →</button></div>}
 {confirm&&<div className={s.result} role="alert"><strong>{confirm==="reset"?"Reset this practice?":"Submit your mock?"}</strong><p>{confirm==="reset"?"All answers and the timer for this paper will be cleared. Other papers are unaffected.":answered+" of "+total+" response fields completed. Submitting locks your response sheet until you reset it."}</p><button className={s.primary} onClick={confirm==="reset"?reset:submit}>{confirm==="reset"?"Clear this attempt":"Confirm submission"}</button> <button className={s.mini} onClick={()=>setConfirm("")}>Cancel</button></div>}
 </section></div><p className={s.hint} style={{marginTop:18}}>These mocks are for the paper-based format, not TOPIK IBT. Public resource links are provided instead of republishing the owner's shared Drive PDFs. Your responses do not sync to the main Hallium account.</p></>}
 <footer className={s.foot}><span>HALLIUM · TOPIK PAST PAPER STUDIO</span><span><a href="/">Home</a> · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a></span></footer></main></div>;
}
